### ISSUE TITLE
Missing endpoint for channel.update sub?

### ISSUE THREAD

**Issue by grofit** [TwitchLib/TwitchLib.PubSub#105]
I am more than happy to be wrong but I couldn't find it on a quick scan through the source etc, 

More info about the endpoint is in here:

https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channel-subscriptions

**Comment by Syzuna** [comment]
EventSub isn't PubSub.
Those are 2 different products.
Available PubSub topics can be found here: https://dev.twitch.tv/docs/pubsub#topics

**Comment by grofit** [comment]
Thanks for clarification will close this then
