### ISSUE TITLE
Uses undocumented 

### ISSUE THREAD

**Issue by da66en** [TwitchLib/TwitchLib.PubSub#106]
PubSub ListenToFollows() does a LISTEN to $"following.{channelId}", but when I look at the PubSub list of topics this isn't shown as a topic.

https://dev.twitch.tv/docs/pubsub#topics

Am I missing something?  It seems like PubSub LISTENS to quite a few topics that aren't documented.

**Comment by Syzuna** [comment]
yes Pubsub still has a lot of legacy undocumented topics (avoid them if possible) that are in the library since forever basically before EventSub was a thing and we didnt want to remove them just yet before EventSub got its Websocket Transport and leave users without an equivalent to use.

**Comment by da66en** [comment]
Darn.  Using the EventSub webhooks doesn't seem feasible in my situation.  Is that the only way to use EventSub, or is another method being developed?

**Comment by Syzuna** [comment]
EventSub will get a Websocket Transport yes.
They said in the last Dev Stream that an open beta for that will be SoonTM
