### ISSUE TITLE
pubsub bad oauth

### ISSUE THREAD

**Issue by THENooBlet** [TwitchLib/TwitchLib.PubSub#35]
im having trouble with my token not working ... giving me bad oauth

heres my code

        pubsub = new TwitchPubSub();
        pubsub.OnPubSubServiceConnected += Pubsub_OnPubSubServiceConnected;
        pubsub.OnBitsReceived += Pubsub_OnBitsReceived;
        pubsub.OnSubscribersOnly += Pubsub_OnSubOnly;
        pubsub.OnSubscribersOnlyOff += Pubsub_onSubonlyoff;
        pubsub.OnWhisper += pubsub_onwisper;
        pubsub.OnListenResponse += Pubsub_OnListenResponse;

        pubsub.Connect();

    }

    private void Pubsub_OnPubSubServiceConnected(object sender, EventArgs e)
    {
        client.SendMessage(Twitch.Default.ChannelName, $"pubsub connected!!!");           
        pubsub.ListenToBitsEvents(Twitch.Default.ChannelID);            
        pubsub.SendTopics(Twitch.Default.BotOauth);            
    }

    private void Pubsub_OnBitsReceived(object sender, OnBitsReceivedArgs e)
    {
        client.SendMessage(Twitch.Default.ChannelName ,$"Just received {e.BitsUsed} bits from {e.Username}. That brings their total to {e.TotalBitsUsed} bits!");
    }

    private void Pubsub_OnListenResponse(object sender, OnListenResponseArgs e)
    {
        if (e.Successful)
            client.SendMessage(Twitch.Default.ChannelName,$"Successfully verified listening to topic: {e.Topic}");
        else
            client.SendMessage(Twitch.Default.ChannelName,$"Failed to listen! Error: {e.Response.Error}");
    }
}

}
:

i left some code out that has to do with client ...(works) but the botoauth being used in send topics is from swiftyspiffy token generator and all scopes are applyed
but i get

newbiestreambot: pubsub connected!!!
newbiestreambot: Failed to listen! Error: ERR_BADAUTH
@THENooBlet

**Comment by NickLarsen** [comment]
Which stream are you attempting to watch and what account is the oAuth token from?

**Comment by callmebackdraft** [comment]
hi there im running into the same issue

i used Oauth tokens from wherever i could get them:
- the bot (which is working with the chat bot)
- the streamer account

**Comment by Bappsack** [comment]
try to get a token with full permissions with the Streamer account here and test if it works:

https://twitchtokengenerator.com/

**Comment by callmebackdraft** [comment]
@Bappsack that is what i did, saddly didnt work

**Comment by Bappsack** [comment]
did u choose the  Custom Scope Token or the Chat Bot Token?

**Comment by callmebackdraft** [comment]
@Bappsack Custom scope and selected all the options possible, then generated the token.

**Comment by swiftyspiffy** [comment]
Hey guys. I’ll run a test when I get home from work and respond back with my results.

**Comment by Bappsack** [comment]
works for me showhow

**Comment by Mahsaap** [comment]
It is saying bad auth before you send the auth

**Comment by callmebackdraft** [comment]
`public void SetupPubSub()
        {
            pubSub.OnPubSubServiceConnected += onPubSubServiceConnected;
            pubSub.OnListenResponse += onListenResponse;

            pubSub.OnChannelSubscription += onChannelSubscription;
            pubSub.OnFollow += onFollow;
            pubSub.OnBitsReceived += PubSub_OnBitsReceived;

            pubSub.ListenToBitsEvents(channel);
            pubSub.ListenToFollows(channel);
            pubSub.ListenToSubscriptions(channel);

            pubSub.Connect();
        }

        private void onPubSubServiceConnected(object sender, EventArgs e)
        {
            Console.WriteLine("PubSub: Connected");
            pubSub.SendTopics(token);
        }

        private void onChannelSubscription(object sender, OnChannelSubscriptionArgs e)
        {
            throw new NotImplementedException();
        }

        private void onFollow(object sender, OnFollowArgs e)
        {
            client.SendMessage("slateknot", "New Follower: " + e.DisplayName);
        }

        private void onListenResponse(object sender, OnListenResponseArgs e)
        {
            if (e.Successful)
                Console.WriteLine($"Successfully verified listening to topic: {e.Topic}");
            else
                Console.WriteLine($"Failed to listen! Error: {e.Response.Error}");
        }`


![image](https://user-images.githubusercontent.com/14372954/65287260-cb800500-db42-11e9-80b0-9b7accb722ea.png)


that is my actual code

**Comment by Mahsaap** [comment]
oh by any chance the channel you are tyring to listen to bits on isnt affiliate or partnered?

**Comment by callmebackdraft** [comment]
Im on 3.0.1

**Comment by Mahsaap** [comment]
ok you both are using bits or more, just verify you are testing this on an affiliate/partnered stream? given that oauth would have to be part of that streamer being tested i believe

**Comment by Mahsaap** [comment]
cause without that im fine

**Comment by callmebackdraft** [comment]
the streamer i am testing on is not an affiliate/partenered account, is that a requirement for the Oauth to work for them ?

**Comment by Mahsaap** [comment]
not to send the oauth but to listen to bits or even subs cause that account has niether, so yes the Oauth will fail. Swifty can verify that for me though. Just to be safe.

**Comment by callmebackdraft** [comment]
@Mahsaap thanks for that info, as soon as i remove the the bits and sub event and just use the follow on that account it autherizes

@swiftyspiffy this is not an issue with twitchlib but it might be helpfull to add this to the documentation

**Comment by Mahsaap** [comment]
thx @callmebackdraft i made a quick pr to the readme for now.

**Comment by Mahsaap** [comment]
#39

**Comment by Mahsaap** [comment]
@THENooBlet this would seem to be the same thing for you. Let us know if you have any more questions. And please close the issue when you feel this is concluded. Thanks.
