### ISSUE TITLE
Missing Feature: Commerce

### ISSUE THREAD

**Issue by Invariel** [TwitchLib/TwitchLib.PubSub#4]
The most recent PubSub documentation includes a section on Commerce, with the "channel-commerce-events-v1.<channel id>" tag.

The given test JSON is as follows:
{
  "type": "MESSAGE",
  "data": {
     "topic": "channel-commerce-events-v1.44322889",
     "message": {
        "user_name": "dallas",
        "display_name": "dallas",
        "channel_name": "twitch",
        "user_id": "44322889",
        "channel_id": "12826",
        "time": "2015-12-19T16:39:57-08:00",
        "item_image_url": "https://...",
        "item_description": "This is a friendly description!",
        "supports_channel": true/false,
        "purchase_message": {
           "message": "A Twitch game is born! Kappa",
           "emotes": [
           {
              "start": 23,
              "end": 7,
              "id": 2867
           }]
        }
     }
  }
}

If I find the time this weekend, I can hammer this out, but if someone wants to tackle it sooner, it's there.

**Comment by Mahsaap** [comment]
Thanks for the heads up! 👍

**Comment by swiftyspiffy** [comment]
Merged #5 Thanks :)
