### ISSUE TITLE
ERR_BADAUTH on Bits/Subs

### ISSUE THREAD

**Issue by JammyGeeza** [TwitchLib/TwitchLib.PubSub#58]
Hey there,

I created a bot a month or so ago that could deal with !commands for my channel and also be able to locally play some Sound Effects when Channel Points were redeemed. 
This has all been working fine, but recently I wanted to control some LEDs when Subs/Bits are received.

Here is the small snippet of code for listening to the relevant events:

```
(1) client.ListenToBitsEvents(“channel_id”);
(2) client.ListenToFollows(“channel_id”);
(3) client.ListenToRedemptions(“channel_id”);

(4) client.SendTopics(“token_here”);
```

With the above code, I get “ERR_BADAUTH” for _all 3_ topics in the onListenResponse event. The _exact_ same thing happens if I replace Line 1 with:
`client.ListenToSubscriptions(“channel_id”);`
However, if I completely remove Line 1, it works just fine and it successfully connects and listens to Channel Point Redemptions and Follows.

I have tried to find an issue on this, but the only resolution I could find was that the account being listened to was not an affiliate account, so here are some things to note in my case:
- The streamer account I am listening to **is** an affiliate account.
- I have tried multiple tokens using the Twitch Token Generator site that includes the `read:bits` topic, and includes all `:subscriptions` topics.
- I have tried a token with **all** topics, which still did not work.

I believe I read somewhere that certain topics require another level of authentication, but I am unsure what it is, where to generate it and where to implement it in the PubSub library.

Apologies if this has been answered before, but any help is appreciated!

Kind regards,

Jamie

**Comment by Mahsaap** [comment]
Subs will require the streamers token to access. So you must use the streamer account to generate that token to access sub events.

**Comment by JammyGeeza** [comment]
Hi @Mahsaap 

The only tokens I have been generating are with the streamer’s account.

**Comment by JammyGeeza** [comment]
> Subs will require the streamers token to access. So you must use the streamer account to generate that token to access sub events.

Hi @Mahsaap 

All the tokens I have been generating have been through the Twitch Token Generator site and I have been using the streamer’s account to generate them.

Is there _another_ token that I need to generate outside of the **Access Token** and **ClientID** to gain access to Sub/Bit events?
If so, how can I generate it and where does it need to be implemented using the PubSub library for it to be authenticated?

**Comment by lualucky** [comment]
I'm having this same issue. Token has every scope enabled from twitchtokengenerator, and channel id works for other topics, but I get ERR_BADAUTH if I listen to subscriptions and/or bits. I'm using the Unity DLL version 1.0.2

**Comment by swiftyspiffy** [comment]
I think this is related to the other issue brought up in the Discord server. I'll be looking into this, this weekend.

**Comment by swiftyspiffy** [comment]
This should be working in the latest Unity build. Sorry about the delay. Will close this. Feel free to reopen if needed.
