### ISSUE TITLE
OnRewardRedeemed only passing unfulfilled events.

### ISSUE THREAD

**Issue by JaINTP** [TwitchLib/TwitchLib.PubSub#82]
First foray into using TwitchLib and I threw together a [stripped down version](https://gist.github.com/JaINTP/deaf60bc2bc42e6fe8f5f868005324d6) of the example [REPO](https://github.com/JayJay1989/TwitchLib.Pubsub.Example) in the ReadMe created by JayJay1989, but for some reason marking a custom reward as complete isn't triggering the `PubSub.OnRewardRedeemed` event at all, let alone with a "FULFILLED" status. I'm not sure if there's something I am doing wrong, or what, but any help would be appreciated.

![25-03-2021_13-50-24_%t](https://user-images.githubusercontent.com/4857160/112416307-25354100-8d71-11eb-8027-792939e6ab79.gif)

**Comment by JayJay1989** [comment]
Are you using the latest dev version?

**Comment by Shaggy84675** [comment]
What I've noticed, there are currently two statuses.
UNFULFILLED - When someone redeem channel points for a reward
ACTION_TAKEN - When is request accepted or rejected in the reward queue.

Unfortunately there's probably no way how to determine if you accepted/rejected reward from the reward queue. If so, please correct me, because I'd like to know too.

**Comment by Mahsaap** [comment]
WIP, I believe swift working on it

**Comment by Shaggy84675** [comment]
Thanks for the info. I've also noticed now, there was an update few days ago. My bot currently using the deprecated method, so maybe the new one will contain more statuses. I'll try to update it later and let you know.

**Comment by JaINTP** [comment]
Sorry for the late reply. I wasn't on the latest dev build but since your mentioning it, I have updated all nuget packages to their latest preview versions, still didn't work, but as I see above it's still a WIP,

Am also seeing Action_taken as Shaggy mentioned when accepting from the reward queue now.

**Comment by swiftyspiffy** [comment]
To be clear, the topic you guys are using is an undocumented one that was implemented quite early in Twitch's development of Channel Points (goes by community points in undocumented land). The documented topic does include the correct status, I believe.

I'll see if I can get the change out this weekend.
