### ISSUE TITLE
LISTEN/UNLISTEN?

### ISSUE THREAD

**Issue by Cocss** [TwitchLib/TwitchLib.PubSub#97]
How can I stop listening to an event. There is a ListenToVideoPlayBack(channelid) event starts listening, but how to make unlisten by (channelid) lol?

**Comment by Syzuna** [comment]
you do a ListenToVideoPlayBack(channelId) again and then do a SendTopics(auth, true), where the second argument is a bool called unlisten, that then unlistens the topics specified before

**Comment by Cocss** [comment]
oh damn, I'm stupid, I didn't notice it. Thanks for the help
